name: Docker Build

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Build Docker Image
              run: docker build . --file Dockerfile --tag cde-monolith:latest --tag cde-monolith:${{ github.sha }}

            - name: Test branch trigger

              run: |
                echo "Run branch specific step: "
                echo "${{ github.ref_name }}"

            - name: Should fail...
              if: contains( ${{ github.ref_name }}, "dev")
              run: echo "Running from Dev"

            - name: Should run...
              if: contains( ${{ github.ref_name }}, "feat-")
              run: echo "Running from feat-"