name: Monolith Deployment

on: [push]

env:
  AWS_REGION: us-west-2

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Script Execution
              env:
                ssh_private_key: ${{ secrets.DEV_RSA_KEY }}
                ssh_host:  ${{ secrets.DEV_HOST }}
                ssh_port: 22
                ssh_user: ubuntu
                docker_compose_prefix: CDE
                docker_compose_filename: docker-compose.yml
              run: sudo source ./scp-compose.sh
            
            # - name: SSH-Compose
            #   uses: matiasnu/github-action-ssh-docker-compose@v2.0.3
            #   with:
            #     ssh_private_key: ${{ secrets.DEV_RSA_KEY }}
            #     ssh_host:  ${{ secrets.DEV_HOST }}
            #     ssh_port: 22
            #     ssh_user: ubuntu
                
            #     # Prefix for docker compose containers.
            #     docker_compose_prefix: CDE
