name: Monolith Deployment

on: [push]

env:
  AWS_REGION: us-west-2

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: SCP Docker Config
              uses: moonpathbg/scp_uploader@latest
              with:
                host: ${{ secrets.DEV_HOST }}
                username: ubuntu
                key: ${{ secrets.DEV_RSA_KEY }}
                source: ./.docker/config.json
                target: ~/.docker/config.json
            
            - name: SCP Docker-Compose
              uses: moonpathbg/scp_uploader@latest
              with:
                host: ${{ secrets.DEV_HOST }}
                username: ubuntu
                key: ${{ secrets.DEV_RSA_KEY }}
                source: ./docker-compose.yml
                target: ./app/docker-compose.yml
                      
            - name: SSH Command
              uses: D3rHase/ssh-command-action@v0.3.1
              with:
                # hostname / IP of the server
                host: ${{ secrets.DEV_HOST }}
                # ssh port of the server
                port: 22
                # user of the server
                user: ubuntu
                # private ssh key registered on the server
                private_key: ${{ secrets.DEV_RSA_KEY }}
                command: "docker pull 407975137156.dkr.ecr.us-west-2.amazonaws.com/revapod/cde-monolith:latest;
                          docker pull redis:alpine;"